routes/admin.php
<?php

Route::group(['middleware' => 'web'], function() {

    Route::group(['as' => 'admin.'], function() {

        Route::get('/clear-cache', function() {

            $exitCode = Artisan::call('config:cache');

            return back();

        })->name('clear-cache');


        Route::get('login', 'Auth\AdminLoginController@showLoginForm')->name('login');

        Route::post('login', 'Auth\AdminLoginController@login')->name('login.post');

        Route::get('logout', 'Auth\AdminLoginController@logout')->name('logout');

        Route::get('/', 'Admin\AdminController@dashboard')->name('dashboard');

        Route::get('forgot_password','Auth\AdminLoginController@showLinkRequestForm')->name('forgot_password.request');

        Route::post('forgot_password_update', 'Auth\AdminLoginController@forgot_password_update')->name('forgot_password.update');

        // Users CRUD Operations

        Route::get('users', 'Admin\AdminUserController@users_index')->name('users.index');

        Route::get('users/create', 'Admin\AdminUserController@users_create')->name('users.create');

        Route::get('users/edit', 'Admin\AdminUserController@users_edit')->name('users.edit');

        Route::post('users/save', 'Admin\AdminUserController@users_save')->name('users.save');

        Route::get('users/view', 'Admin\AdminUserController@users_view')->name('users.view');

        Route::get('users/delete', 'Admin\AdminUserController@users_delete')->name('users.delete');

        Route::get('users/status', 'Admin\AdminUserController@users_status')->name('users.status');

        Route::get('users/excel','Admin\AdminUserController@users_excel')->name('users.excel');

        Route::get('users/verify', 'Admin\AdminUserController@users_verify_status')->name('users.verify');

        Route::get('users/export/','Admin\AdminUserController@users_export')->name('users.export');

        Route::get('invested_projects', 'Admin\AdminUserController@invested_projects')->name('invested_projects');

        Route::get('invested_projects/view', 'Admin\AdminUserController@invested_projects_view')->name('invested_projects.view');

        Route::get('invested_projects/claim', 'Admin\AdminUserController@invested_projects_claim')->name('invested_projects.claim');
        
        Route::post('/users/bulk_action', 'Admin\AdminUserController@users_bulk_action')->name('users.bulk_action');

        Route::get('/users/staked_amount', 'Admin\AdminUserController@users_staked_amount')->name('users.staked_amount');

        
        Route::post('subscriptions/bulk_action', 'Admin\SubscriptionController@subscriptions_bulk_action')->name('subscriptions.bulk_action');


        Route::get('profile', 'Admin\AdminAccountController@profile')->name('profile');

        Route::post('profile/save', 'Admin\AdminAccountController@profile_save')->name('profile.save');

        Route::post('change/password', 'Admin\AdminAccountController@change_password')->name('change.password');
        
        Route::get('transactions/getaccount', 'Admin\BlockOperationController@transactions_getaccount')->name('transactions.getaccount');

        Route::post('transactions/history', 'Admin\BlockOperationController@transactions_index')->name('transactions.index');

        Route::get('wallets/view', 'Admin\BlockOperationController@transactions_getaccount')->name('wallets.view');

        // settings

        Route::get('control', 'Admin\AdminSettingController@settings_control')->name('settings-control'); 

        Route::get('settings', 'Admin\AdminSettingController@settings')->name('settings'); 

        Route::post('settings/save', 'Admin\AdminSettingController@settings_save')->name('settings.save'); 

        Route::post('env_settings','Admin\AdminSettingController@env_settings_save')->name('env-settings.save');

        // Documents CRUD operations

        Route::get('documents/index', 'Admin\AdminLookupController@documents_index')->name('documents.index');

        Route::get('documents/create', 'Admin\AdminLookupController@documents_create')->name('documents.create');
 
        Route::get('documents/edit', 'Admin\AdminLookupController@documents_edit')->name('documents.edit');
 
        Route::post('documents/save', 'Admin\AdminLookupController@documents_save')->name('documents.save');
 
        Route::get('documents/view', 'Admin\AdminLookupController@documents_view')->name('documents.view');
 
        Route::get('documents/delete', 'Admin\AdminLookupController@documents_delete')->name('documents.delete');
 
        Route::get('documents/status', 'Admin\AdminLookupController@documents_status')->name('documents.status');
 
        //user documents 

        Route::get('user-documents', 'Admin\AdminUserController@user_documents_index')->name('user_documents.index');

        Route::get('user-document', 'Admin\AdminUserController@user_documents_view')->name('user_documents.view');

        Route::get('user-documents/verify', 'Admin\AdminUserController@user_documents_verify')->name('user_documents.verify');

        // STATIC PAGES

        Route::get('static_pages' , 'Admin\AdminLookupController@static_pages_index')->name('static_pages.index');

        Route::get('static_pages/create', 'Admin\AdminLookupController@static_pages_create')->name('static_pages.create');

        Route::get('static_pages/edit', 'Admin\AdminLookupController@static_pages_edit')->name('static_pages.edit');

        Route::post('static_pages/save', 'Admin\AdminLookupController@static_pages_save')->name('static_pages.save');

        Route::get('static_pages/delete', 'Admin\AdminLookupController@static_pages_delete')->name('static_pages.delete');

        Route::get('static_pages/view', 'Admin\AdminLookupController@static_pages_view')->name('static_pages.view');

        Route::get('static_pages/status', 'Admin\AdminLookupController@static_pages_status_change')->name('static_pages.status');

        //faq CRUD
        Route::get('faqs', 'Admin\AdminLookupController@faqs_index')->name('faqs.index');

        Route::get('faqs/create', 'Admin\AdminLookupController@faqs_create')->name('faqs.create');

        Route::get('faqs/edit', 'Admin\AdminLookupController@faqs_edit')->name('faqs.edit');

        Route::post('faqs/save', 'Admin\AdminLookupController@faqs_save')->name('faqs.save');

        Route::get('faqs/view', 'Admin\AdminLookupController@faqs_view')->name('faqs.view');

        Route::get('faqs/delete', 'Admin\AdminLookupController@faqs_delete')->name('faqs.delete');

        Route::get('faqs/status', 'Admin\AdminLookupController@faqs_status')->name('faqs.status');
        //faq end

        Route::get('projects', 'Admin\AdminProjectController@projects_index')->name('projects.index');

        Route::get('projects/create', 'Admin\AdminProjectController@projects_create')->name('projects.create');

        Route::get('projects/edit', 'Admin\AdminProjectController@projects_edit')->name('projects.edit');

        Route::post('projects/save', 'Admin\AdminProjectController@projects_save')->name('projects.save');

        Route::get('projects/view', 'Admin\AdminProjectController@projects_view')->name('projects.view');

        Route::get('projects/delete', 'Admin\AdminProjectController@projects_delete')->name('projects.delete');

        Route::get('projects/status', 'Admin\AdminProjectController@projects_status')->name('projects.status');

        Route::get('projects/publish_status', 'Admin\AdminProjectController@projects_publish_status')->name('projects.publish_status');

        // Subscriptions
        
        Route::get('subscriptions', 'Admin\SubscriptionController@subscriptions_index')->name('subscriptions.index');

        Route::get('subscriptions/create', 'Admin\SubscriptionController@subscriptions_create')->name('subscriptions.create');

        Route::get('subscriptions/edit', 'Admin\SubscriptionController@subscriptions_edit')->name('subscriptions.edit');

        Route::post('subscriptions/save', 'Admin\SubscriptionController@subscriptions_save')->name('subscriptions.save');

        Route::get('subscriptions/view', 'Admin\SubscriptionController@subscriptions_view')->name('subscriptions.view');

        Route::get('subscriptions/delete', 'Admin\SubscriptionController@subscriptions_delete')->name('subscriptions.delete');

        Route::get('subscriptions/status', 'Admin\SubscriptionController@subscriptions_status')->name('subscriptions.status');

        // Subscription Payments

        Route::get('subscription_payments/index','Admin\SubscriptionController@subscription_payments_index')->name('subscription_payments.index');

        Route::get('subscription_payments/view','Admin\SubscriptionController@subscription_payments_view')->name('subscription_payments.view');

        Route::get('revenues/dashboard','Admin\AdminRevenueController@revenues_dashboard')->name('revenues.dashboard');

        // Project Payments

        Route::get('project_payments/index','Admin\AdminProjectController@project_payments_index')->name('project_payments.index');

        Route::get('project_payments/view','Admin\AdminProjectController@project_payments_view')->name('project_payments.view');


        Route::get('token_payments/index','Admin\AdminRevenueController@token_payments_index')->name('token_payments.index');

        Route::get('token_payments/view','Admin\AdminRevenueController@token_payments_view')->name('token_payments.view');


        Route::get('project-view','Admin\AdminProjectController@projects_view_for_web')->name('projects_view_for_web');

        // Ajax Functions


        Route::post('projects/pool_contract_save','Admin\AdminProjectController@projects_pool_contract_save')->name('projects_pool_contract_save');

        Route::post('projects_burn_access_update','Admin\AdminProjectController@projects_burn_access_update')->name('projects_burn_access_update');

routes/web.php
<?php

use  App\Http\Controllers\UserAuthController;

use  App\Http\Controllers\AdminAuthController;

use  App\Http\Controllers\ReactController;

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::view('/{path?}', 'app');

// Route::get('/{path?}', [
//     'uses' => 'ReactController@show',
//     'as' => 'react',
//     'where' => ['path' => 'burn|mint|new']
// ]);

// Route::get('/project/{path?}', function () {
//     return view('app');
// })->where('path', '.*');

// 
// // Route::get('/{url?}', function () {
//     return view('app');
// })->where('', 'list');

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/test', function(){
    return view('test');
});

// User

Route::get('/', [UserAuthController::class, 'index'])->name('user.home') ->middleware('auth:web');

Route::get('/login', [UserAuthController::class, 'login'])->name('user.login');

Route::post('/login', [UserAuthController::class, 'handleLogin'])->name('user.handleLogin');

Route::get('/logout', [UserAuthController::class, 'index'])->name('user.logout');

Route::get('email', 'SampleController@email_check');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

use App\Helpers\Helper;

use Setting;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    protected $appends = ['user_id', 'user_unique_id'];
    
    public function getUserIdAttribute() {

        return $this->id;
    }

    public function getUserUniqueIdAttribute() {

        return $this->unique_id;
    }
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'id', 'unique_id'
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Scope a query to only include active users.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeApproved($query) {

        $query->where('users.status', USER_APPROVED)->where('is_email_verified', USER_EMAIL_VERIFIED);

        return $query;

    }

    public function userCards() {

        return $this->hasMany(UserCard::class);
    }

    public function userDocuments() {

        return $this->hasMany(UserDocument::class);
    }

    public function subscriptionPayments() {

        return $this->hasMany(SubscriptionPayment::class);
    }

    public function investedProjects() {

        return $this->hasMany(InvestedProject::class);
    }

    public function projects() {

        return $this->hasMany(Project::class);
    }

    public function projectPayments() {

        return $this->hasMany(ProjectPayment::class);
    }

    public function tokenPayments() {

        return $this->hasMany(TokenPayment::class);
    }

    public function projectOwnerTransactions() {

        return $this->hasMany(ProjectOwnerTransaction::class);
    }
    
    public static function boot() {

        parent::boot();

        static::creating(function ($model) {

            $model->attributes['token'] = Helper::generate_token();

            $model->attributes['token_expiry'] = Helper::generate_token_expiry();

            $model->attributes['status'] = USER_APPROVED;

             if (Setting::get('is_account_email_verification') == YES && envfile('MAIL_USERNAME') && envfile('MAIL_PASSWORD')) { 

                $model->generateEmailCode();            

            } else {
                
                $model->attributes['is_email_verified'] = USER_EMAIL_VERIFIED;

            }

        });

        static::created(function($model) {
            
            $model->attributes['is_email_notification'] = $model->attributes['is_push_notification'] = YES;

            $model->attributes['unique_id'] = routefreestring(strtolower($model->attributes['name'] ?: rand(1,10000).rand(1,10000))).'-'.$model->attributes['id'];

            $model->save();
        
        });

        static::updating(function($model) {

        });

        static::deleting(function ($model){

            Helper::storage_delete_file($model->picture, PROFILE_PATH_USER);

            $model->userCards()->delete();

            $model->userDocuments()->delete();

            $model->subscriptionPayments()->delete();

            foreach ($model->projects as $key => $project) {
                $project->delete();
            }

            $model->projectPayments()->delete();

            $model->tokenPayments()->delete();

            $model->projectOwnerTransactions()->delete();

        });

    }

    /**
     * Generates Token and Token Expiry
     * 
     * @return bool returns true if successful. false on failure.
     */

    protected function generateEmailCode() {

        $this->attributes['verification_code'] = Helper::generate_email_code();

        $this->attributes['verification_code_expiry'] = Helper::generate_email_expiry();

        return true;
    
    }
}

resources/views/admin/revenues/users/staked_amount.blade.php
@extends('layouts.admin')

@section('title', tr('users'))

@section('content-header', tr('users'))

@section('breadcrumb')

    <li class="breadcrumb-item active">
        <a href="{{route('admin.users.index')}}">{{ tr('users') }}</a>
    </li>

    <li class="breadcrumb-item">{{$title ?? tr('view_users')}}</li>

@endsection

@section('content')

<div class="row">   

    <div class="col-md-12">
         
        <div class="box">

            <div class="box-header with-border">
                <h3 class="box-title">{{$title ?? tr('view_users')}}</h3>

            </div>

            <!-- /.box-header -->
            <div class="box-body">

                <div class="callout bg-pale-secondary">
                    <h4>Notes:</h4>
                    <p>
                        <ul>
                            <li>User can be both Project owner(The person who add the token for presale or IDO) and Investor(The person who invest the project token or The tokens added by the Project owner)</li>
                            <li>User A can be a project owner as well as investor. </li>
                            <li>User A invest in any of the project token - Then User A will be investor. </li>
                            <li>User A add any project into launch page - Then user A will be Project owner. </li>
                        </ul>
                    </p>
                </div>

                <form method="GET" action="{{route('admin.users.staked_amount')}}">

                    <div class="row">


                        <div class="col-xs-12 col-sm-12 col-lg-12 col-md-12 resp-mrg-btm-md">
                            @if(Request::has('search_key'))
                            <p class="text-muted">Search results for <b>{{Request::get('search_key')}}</b></p>
                            @endif
                        </div>

                        <div class="col-xs-12 col-sm-12 col-lg-3 col-md-3 offset-lg-3 offset-md-3 md-full-width resp-mrg-btm-md">

                        </div>

                        <div class="col-xs-12 col-sm-12 col-lg-6 col-md-12">

                            <div class="input-group">

                                <input type="text" class="form-control" name="search_key" value="{{Request::get('search_key')??''}}" placeholder="{{tr('users_search_placeholder')}}"> 

                                <span class="input-group-btn">
                                    &nbsp

                                    <button type="submit" class="btn btn-default reset-btn">
                                        <i class="fa fa-search" aria-hidden="true"></i>
                                    </button>

                                    <a href="{{route('admin.users.staked_amount')}}" class="btn btn-default reset-btn">
                                        <span> <i class="fa fa-eraser" aria-hidden="true"></i>
                                        </span>
                                    </a>

                                </span>

                            </div>

                        </div>

                    </div>

                </form>
                <br>

                <div class="table-responsive">
                    
                    <table id="example2" class="table table-bordered table-hover display nowrap margin-top-10 w-p100">

                        <thead>
                            <tr>
                                <th>{{tr('s_no')}}</th>
                                <th>{{tr('name')}}</th>
                                <th>{{tr('wallet_address')}}</th>
                                <th>{{tr('staked_amount')}}</th>
                                <th>{{tr('tier')}}</th>
                                <th>{{tr('action')}}</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach($users as $i => $user)

                                <tr>

                                    <td>{{ $i+$users->firstItem() }}</td>

                                    <td class="white-space-nowrap">
                                        <a href="{{route('admin.users.view' , ['user_id' => $user->id])}}" class="custom-a">
                                            {{$user->name ?: tr('not_available')}}
                                        </a>
                                        
                                    </td>

                                    <td>
                                        {{ $user->wallet_address ?: tr('not_available') }}
                                    </td>

                                    <td>
                                        {{ $user->staked_amount ?? tr('not_available') }} BUSDX
                                    </td>

                                    <td>
                                        <a href="{{ (subscription_tire($user->staked_amount ?? 0)['subscription_link']) ?? tr('n_a') }}" class="custom-a">
                                            {{ (subscription_tire($user->staked_amount ?? 0)['tire']) ?? tr('n_a') }}
                                        </a>
                                    </td>
                                   
                                    <td>

                                        <div class="btn-group" role="group">

                                            <a href="{{route('admin.users.view' , ['user_id' => $user->id])}}" class="btn btn-primary"><i class="ft-settings icon-left"></i> {{ tr('view') }}</a>

                                        </div>

                                    </td>

                                </tr>
                                
                            @endforeach                         
                        </tbody>                       
                    </table>
                
                </div>

            </div>

            <div class="box-footer clearfix">
                    
                <div class="pull-right rd-flex">
                    {{$users->appends(request()->input())->links('pagination::bootstrap-4')}}
                </div>
            </div>

        </div>
    </div>
</div>

@endsection