routes/admin.php
<?php

Route::group(['middleware' => 'web'], function() {

    Route::group(['as' => 'admin.'], function() {

        Route::get('/clear-cache', function() {

            $exitCode = Artisan::call('config:cache');

            return back();

        })->name('clear-cache');


        Route::get('login', 'Auth\AdminLoginController@showLoginForm')->name('login');

        Route::post('login', 'Auth\AdminLoginController@login')->name('login.post');

        Route::get('logout', 'Auth\AdminLoginController@logout')->name('logout');

        Route::get('/', 'Admin\AdminController@dashboard')->name('dashboard');

        Route::get('forgot_password','Auth\AdminLoginController@showLinkRequestForm')->name('forgot_password.request');

        Route::post('forgot_password_update', 'Auth\AdminLoginController@forgot_password_update')->name('forgot_password.update');

        // Users CRUD Operations

        Route::get('users', 'Admin\AdminUserController@users_index')->name('users.index');

        Route::get('users/create', 'Admin\AdminUserController@users_create')->name('users.create');

        Route::get('users/edit', 'Admin\AdminUserController@users_edit')->name('users.edit');

        Route::post('users/save', 'Admin\AdminUserController@users_save')->name('users.save');

        Route::get('users/view', 'Admin\AdminUserController@users_view')->name('users.view');

        Route::get('users/delete', 'Admin\AdminUserController@users_delete')->name('users.delete');

        Route::get('users/status', 'Admin\AdminUserController@users_status')->name('users.status');

        Route::get('users/excel','Admin\AdminUserController@users_excel')->name('users.excel');

        Route::get('users/verify', 'Admin\AdminUserController@users_verify_status')->name('users.verify');

        Route::get('users/export/','Admin\AdminUserController@users_export')->name('users.export');

        Route::get('invested_projects', 'Admin\AdminUserController@invested_projects')->name('invested_projects');

        Route::get('invested_projects/view', 'Admin\AdminUserController@invested_projects_view')->name('invested_projects.view');

        Route::get('invested_projects/claim', 'Admin\AdminUserController@invested_projects_claim')->name('invested_projects.claim');
        
        Route::post('/users/bulk_action', 'Admin\AdminUserController@users_bulk_action')->name('users.bulk_action');

        Route::get('/users/staked_amount', 'Admin\AdminUserController@users_staked_amount')->name('users.staked_amount');

        
        Route::post('subscriptions/bulk_action', 'Admin\SubscriptionController@subscriptions_bulk_action')->name('subscriptions.bulk_action');


        Route::get('profile', 'Admin\AdminAccountController@profile')->name('profile');

        Route::post('profile/save', 'Admin\AdminAccountController@profile_save')->name('profile.save');

        Route::post('change/password', 'Admin\AdminAccountController@change_password')->name('change.password');
        
        Route::get('transactions/getaccount', 'Admin\BlockOperationController@transactions_getaccount')->name('transactions.getaccount');

        Route::post('transactions/history', 'Admin\BlockOperationController@transactions_index')->name('transactions.index');

        Route::get('wallets/view', 'Admin\BlockOperationController@transactions_getaccount')->name('wallets.view');

        // settings

        Route::get('control', 'Admin\AdminSettingController@settings_control')->name('settings-control'); 

        Route::get('settings', 'Admin\AdminSettingController@settings')->name('settings'); 

        Route::post('settings/save', 'Admin\AdminSettingController@settings_save')->name('settings.save'); 

        Route::post('env_settings','Admin\AdminSettingController@env_settings_save')->name('env-settings.save');

        // Documents CRUD operations

        Route::get('documents/index', 'Admin\AdminLookupController@documents_index')->name('documents.index');

        Route::get('documents/create', 'Admin\AdminLookupController@documents_create')->name('documents.create');
 
        Route::get('documents/edit', 'Admin\AdminLookupController@documents_edit')->name('documents.edit');
 
        Route::post('documents/save', 'Admin\AdminLookupController@documents_save')->name('documents.save');
 
        Route::get('documents/view', 'Admin\AdminLookupController@documents_view')->name('documents.view');
 
        Route::get('documents/delete', 'Admin\AdminLookupController@documents_delete')->name('documents.delete');
 
        Route::get('documents/status', 'Admin\AdminLookupController@documents_status')->name('documents.status');
 
        //user documents 

        Route::get('user-documents', 'Admin\AdminUserController@user_documents_index')->name('user_documents.index');

        Route::get('user-document', 'Admin\AdminUserController@user_documents_view')->name('user_documents.view');

        Route::get('user-documents/verify', 'Admin\AdminUserController@user_documents_verify')->name('user_documents.verify');

        // STATIC PAGES

        Route::get('static_pages' , 'Admin\AdminLookupController@static_pages_index')->name('static_pages.index');

        Route::get('static_pages/create', 'Admin\AdminLookupController@static_pages_create')->name('static_pages.create');

        Route::get('static_pages/edit', 'Admin\AdminLookupController@static_pages_edit')->name('static_pages.edit');

        Route::post('static_pages/save', 'Admin\AdminLookupController@static_pages_save')->name('static_pages.save');

        Route::get('static_pages/delete', 'Admin\AdminLookupController@static_pages_delete')->name('static_pages.delete');

        Route::get('static_pages/view', 'Admin\AdminLookupController@static_pages_view')->name('static_pages.view');

        Route::get('static_pages/status', 'Admin\AdminLookupController@static_pages_status_change')->name('static_pages.status');

        //faq CRUD
        Route::get('faqs', 'Admin\AdminLookupController@faqs_index')->name('faqs.index');

        Route::get('faqs/create', 'Admin\AdminLookupController@faqs_create')->name('faqs.create');

        Route::get('faqs/edit', 'Admin\AdminLookupController@faqs_edit')->name('faqs.edit');

        Route::post('faqs/save', 'Admin\AdminLookupController@faqs_save')->name('faqs.save');

        Route::get('faqs/view', 'Admin\AdminLookupController@faqs_view')->name('faqs.view');

        Route::get('faqs/delete', 'Admin\AdminLookupController@faqs_delete')->name('faqs.delete');

        Route::get('faqs/status', 'Admin\AdminLookupController@faqs_status')->name('faqs.status');
        //faq end

        Route::get('projects', 'Admin\AdminProjectController@projects_index')->name('projects.index');

        Route::get('projects/create', 'Admin\AdminProjectController@projects_create')->name('projects.create');

        Route::get('projects/edit', 'Admin\AdminProjectController@projects_edit')->name('projects.edit');

        Route::post('projects/save', 'Admin\AdminProjectController@projects_save')->name('projects.save');

        Route::get('projects/view', 'Admin\AdminProjectController@projects_view')->name('projects.view');

        Route::get('projects/delete', 'Admin\AdminProjectController@projects_delete')->name('projects.delete');

        Route::get('projects/status', 'Admin\AdminProjectController@projects_status')->name('projects.status');

        Route::get('projects/publish_status', 'Admin\AdminProjectController@projects_publish_status')->name('projects.publish_status');

        // Subscriptions
        
        Route::get('subscriptions', 'Admin\SubscriptionController@subscriptions_index')->name('subscriptions.index');

        Route::get('subscriptions/create', 'Admin\SubscriptionController@subscriptions_create')->name('subscriptions.create');

        Route::get('subscriptions/edit', 'Admin\SubscriptionController@subscriptions_edit')->name('subscriptions.edit');

        Route::post('subscriptions/save', 'Admin\SubscriptionController@subscriptions_save')->name('subscriptions.save');

        Route::get('subscriptions/view', 'Admin\SubscriptionController@subscriptions_view')->name('subscriptions.view');

        Route::get('subscriptions/delete', 'Admin\SubscriptionController@subscriptions_delete')->name('subscriptions.delete');

        Route::get('subscriptions/status', 'Admin\SubscriptionController@subscriptions_status')->name('subscriptions.status');

        // Subscription Payments

        Route::get('subscription_payments/index','Admin\SubscriptionController@subscription_payments_index')->name('subscription_payments.index');

        Route::get('subscription_payments/view','Admin\SubscriptionController@subscription_payments_view')->name('subscription_payments.view');

        Route::get('revenues/dashboard','Admin\AdminRevenueController@revenues_dashboard')->name('revenues.dashboard');

        // Project Payments

        Route::get('project_payments/index','Admin\AdminProjectController@project_payments_index')->name('project_payments.index');

        Route::get('project_payments/view','Admin\AdminProjectController@project_payments_view')->name('project_payments.view');


        Route::get('token_payments/index','Admin\AdminRevenueController@token_payments_index')->name('token_payments.index');

        Route::get('token_payments/view','Admin\AdminRevenueController@token_payments_view')->name('token_payments.view');


        Route::get('project-view','Admin\AdminProjectController@projects_view_for_web')->name('projects_view_for_web');

        // Ajax Functions


        Route::post('projects/pool_contract_save','Admin\AdminProjectController@projects_pool_contract_save')->name('projects_pool_contract_save');

        Route::post('projects_burn_access_update','Admin\AdminProjectController@projects_burn_access_update')->name('projects_burn_access_update');

routes/web.php
<?php

use  App\Http\Controllers\UserAuthController;

use  App\Http\Controllers\AdminAuthController;

use  App\Http\Controllers\ReactController;

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::view('/{path?}', 'app');

// Route::get('/{path?}', [
//     'uses' => 'ReactController@show',
//     'as' => 'react',
//     'where' => ['path' => 'burn|mint|new']
// ]);

// Route::get('/project/{path?}', function () {
//     return view('app');
// })->where('path', '.*');

// 
// // Route::get('/{url?}', function () {
//     return view('app');
// })->where('', 'list');

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/test', function(){
    return view('test');
});

// User

Route::get('/', [UserAuthController::class, 'index'])->name('user.home') ->middleware('auth:web');

Route::get('/login', [UserAuthController::class, 'login'])->name('user.login');

Route::post('/login', [UserAuthController::class, 'handleLogin'])->name('user.handleLogin');

Route::get('/logout', [UserAuthController::class, 'index'])->name('user.logout');

Route::get('email', 'SampleController@email_check');

resources/views/admin/transactions/getaccount.blade.php
@extends('layouts.admin')

@section('content-header')

Users

@endsection

@section('breadcrumb')

<a href="{{route('admin.users.index')}}" class="btn px-15 btn-primary">
	<i class="las la-eye fs-16"></i> Transcations
</a>

@endsection

@section('content')

<div class="row">
    <div class="col-lg-12">
        <div class="card card-Vertical card-default card-md mb-4">
            <div class="card-header">
                <h6>Add User</h6>
            </div>
            <div class="card-body py-md-30">
                <form method="POST" action="{{ route('admin.transactions.index') }}" enctype="multipart/form-data">
                    
                    @csrf
                    
                    <div class="row">
                        <div class="col-md-6 mb-25">
                             <label for="for_firstname">Enter Your Account Address*</label>
                            <input type="text" class="form-control ih-medium ip-gray radius-xs b-light px-15" placeholder="Account Address" name="account" required>
                        </div>

                    </div>

                    <div class="col-md-6">
                        <div class="layout-button mt-0">

                            <button type="reset" class="btn btn-warning btn-default btn-squared px-30">Reset</button>

                            <button type="submit" class="btn btn-primary btn-default btn-squared px-30">Submit</button>
                        </div>
                    
                    </div>
                    
                </form>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/admin/transactions/index.blade.php
@extends('layouts.admin')

@section('content-header')

Transactions

@endsection

@section('breadcrumb')

<a href="{{route('admin.transactions.getaccount')}}" class="btn px-15 btn-primary">
	<i class="las la-eye fs-16"></i> Transcations
</a>

@endsection

@section('content')

<div class="row">
    <div class="col-12">

        <div class="card">
            <div class="card-header color-dark fw-500">
                List Of Transactions
            </div>
            <div class="card-body p-0">
                <div class="table4  p-25 bg-white mb-30">
                    <div class="table-responsive">

                        @if($transactions)
                        
                        <table class="table mb-0">
                            <thead>
                                <tr class="userDatatable-header">
                                    <th>
                                        <span class="userDatatable-title">S.No</span>
                                    </th>
                                    <th>
                                        <span class="userDatatable-title">From | To</span>
                                    </th>
                                    <th>
                                        <span class="userDatatable-title">Value</span>
                                    </th>
                                    <!-- <th>
                                        <span class="userDatatable-title">Gas Value</span>
                                    </th> -->
                                    <th>
                                        <span class="userDatatable-title">Service Fee</span>
                                    </th>

                                    <th>
                                        <span class="userDatatable-title">Method</span>
                                    </th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach($transactions as $i => $transaction)

                                <tr>
                                    <td>
                                        <div class="userDatatable-content">
                                            {{$i+1}}
                                        </div>
                                    </td>

                                    <td>
                                        <div class="userDatatable-content">
                                            From: {{$transaction->from}}
                                            <br>
                                            To: {{$transaction->to}}

                                        </div>
                                    </td>
                                    <td>
                                        <div class="userDatatable-content">
                                            {{bcdiv($transaction->value,'1000000000000000000', 4)}} Ether
                                        </div>
                                    </td>
                                 
                                    <td>
                                        <div class="userDatatable-content">
                                            {{bcdiv($transaction->gas * $transaction->gasPrice,'1000000000000000000', 6)}}
                                        </div>
                                    </td>

                                    <td>
                                        Actions
                                    </td>
                                </tr>

                                @endforeach

                            </tbody>
                        
                        </table>

                        @else

                        @endif
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>


@endsection