routes/admin.php
<?php

Route::group(['middleware' => 'web'], function() {

    Route::group(['as' => 'admin.'], function() {

        Route::get('/clear-cache', function() {

            $exitCode = Artisan::call('config:cache');

            return back();

        })->name('clear-cache');


        Route::get('login', 'Auth\AdminLoginController@showLoginForm')->name('login');

        Route::post('login', 'Auth\AdminLoginController@login')->name('login.post');

        Route::get('logout', 'Auth\AdminLoginController@logout')->name('logout');

        Route::get('/', 'Admin\AdminController@dashboard')->name('dashboard');

        Route::get('forgot_password','Auth\AdminLoginController@showLinkRequestForm')->name('forgot_password.request');

        Route::post('forgot_password_update', 'Auth\AdminLoginController@forgot_password_update')->name('forgot_password.update');

        // Users CRUD Operations

        Route::get('users', 'Admin\AdminUserController@users_index')->name('users.index');

        Route::get('users/create', 'Admin\AdminUserController@users_create')->name('users.create');

        Route::get('users/edit', 'Admin\AdminUserController@users_edit')->name('users.edit');

        Route::post('users/save', 'Admin\AdminUserController@users_save')->name('users.save');

        Route::get('users/view', 'Admin\AdminUserController@users_view')->name('users.view');

        Route::get('users/delete', 'Admin\AdminUserController@users_delete')->name('users.delete');

        Route::get('users/status', 'Admin\AdminUserController@users_status')->name('users.status');

        Route::get('users/excel','Admin\AdminUserController@users_excel')->name('users.excel');

        Route::get('users/verify', 'Admin\AdminUserController@users_verify_status')->name('users.verify');

        Route::get('users/export/','Admin\AdminUserController@users_export')->name('users.export');

        Route::get('invested_projects', 'Admin\AdminUserController@invested_projects')->name('invested_projects');

        Route::get('invested_projects/view', 'Admin\AdminUserController@invested_projects_view')->name('invested_projects.view');

        Route::get('invested_projects/claim', 'Admin\AdminUserController@invested_projects_claim')->name('invested_projects.claim');
        
        Route::post('/users/bulk_action', 'Admin\AdminUserController@users_bulk_action')->name('users.bulk_action');

        Route::get('/users/staked_amount', 'Admin\AdminUserController@users_staked_amount')->name('users.staked_amount');

        
        Route::post('subscriptions/bulk_action', 'Admin\SubscriptionController@subscriptions_bulk_action')->name('subscriptions.bulk_action');


        Route::get('profile', 'Admin\AdminAccountController@profile')->name('profile');

        Route::post('profile/save', 'Admin\AdminAccountController@profile_save')->name('profile.save');

        Route::post('change/password', 'Admin\AdminAccountController@change_password')->name('change.password');
        
        Route::get('transactions/getaccount', 'Admin\BlockOperationController@transactions_getaccount')->name('transactions.getaccount');

        Route::post('transactions/history', 'Admin\BlockOperationController@transactions_index')->name('transactions.index');

        Route::get('wallets/view', 'Admin\BlockOperationController@transactions_getaccount')->name('wallets.view');

        // settings

        Route::get('control', 'Admin\AdminSettingController@settings_control')->name('settings-control'); 

        Route::get('settings', 'Admin\AdminSettingController@settings')->name('settings'); 

        Route::post('settings/save', 'Admin\AdminSettingController@settings_save')->name('settings.save'); 

        Route::post('env_settings','Admin\AdminSettingController@env_settings_save')->name('env-settings.save');

        // Documents CRUD operations

        Route::get('documents/index', 'Admin\AdminLookupController@documents_index')->name('documents.index');

        Route::get('documents/create', 'Admin\AdminLookupController@documents_create')->name('documents.create');
 
        Route::get('documents/edit', 'Admin\AdminLookupController@documents_edit')->name('documents.edit');
 
        Route::post('documents/save', 'Admin\AdminLookupController@documents_save')->name('documents.save');
 
        Route::get('documents/view', 'Admin\AdminLookupController@documents_view')->name('documents.view');
 
        Route::get('documents/delete', 'Admin\AdminLookupController@documents_delete')->name('documents.delete');
 
        Route::get('documents/status', 'Admin\AdminLookupController@documents_status')->name('documents.status');
 
        //user documents 

        Route::get('user-documents', 'Admin\AdminUserController@user_documents_index')->name('user_documents.index');

        Route::get('user-document', 'Admin\AdminUserController@user_documents_view')->name('user_documents.view');

        Route::get('user-documents/verify', 'Admin\AdminUserController@user_documents_verify')->name('user_documents.verify');

        // STATIC PAGES

        Route::get('static_pages' , 'Admin\AdminLookupController@static_pages_index')->name('static_pages.index');

        Route::get('static_pages/create', 'Admin\AdminLookupController@static_pages_create')->name('static_pages.create');

        Route::get('static_pages/edit', 'Admin\AdminLookupController@static_pages_edit')->name('static_pages.edit');

        Route::post('static_pages/save', 'Admin\AdminLookupController@static_pages_save')->name('static_pages.save');

        Route::get('static_pages/delete', 'Admin\AdminLookupController@static_pages_delete')->name('static_pages.delete');

        Route::get('static_pages/view', 'Admin\AdminLookupController@static_pages_view')->name('static_pages.view');

        Route::get('static_pages/status', 'Admin\AdminLookupController@static_pages_status_change')->name('static_pages.status');

        //faq CRUD
        Route::get('faqs', 'Admin\AdminLookupController@faqs_index')->name('faqs.index');

        Route::get('faqs/create', 'Admin\AdminLookupController@faqs_create')->name('faqs.create');

        Route::get('faqs/edit', 'Admin\AdminLookupController@faqs_edit')->name('faqs.edit');

        Route::post('faqs/save', 'Admin\AdminLookupController@faqs_save')->name('faqs.save');

        Route::get('faqs/view', 'Admin\AdminLookupController@faqs_view')->name('faqs.view');

        Route::get('faqs/delete', 'Admin\AdminLookupController@faqs_delete')->name('faqs.delete');

        Route::get('faqs/status', 'Admin\AdminLookupController@faqs_status')->name('faqs.status');
        //faq end

        Route::get('projects', 'Admin\AdminProjectController@projects_index')->name('projects.index');

        Route::get('projects/create', 'Admin\AdminProjectController@projects_create')->name('projects.create');

        Route::get('projects/edit', 'Admin\AdminProjectController@projects_edit')->name('projects.edit');

        Route::post('projects/save', 'Admin\AdminProjectController@projects_save')->name('projects.save');

        Route::get('projects/view', 'Admin\AdminProjectController@projects_view')->name('projects.view');

        Route::get('projects/delete', 'Admin\AdminProjectController@projects_delete')->name('projects.delete');

        Route::get('projects/status', 'Admin\AdminProjectController@projects_status')->name('projects.status');

        Route::get('projects/publish_status', 'Admin\AdminProjectController@projects_publish_status')->name('projects.publish_status');

        // Subscriptions
        
        Route::get('subscriptions', 'Admin\SubscriptionController@subscriptions_index')->name('subscriptions.index');

        Route::get('subscriptions/create', 'Admin\SubscriptionController@subscriptions_create')->name('subscriptions.create');

        Route::get('subscriptions/edit', 'Admin\SubscriptionController@subscriptions_edit')->name('subscriptions.edit');

        Route::post('subscriptions/save', 'Admin\SubscriptionController@subscriptions_save')->name('subscriptions.save');

        Route::get('subscriptions/view', 'Admin\SubscriptionController@subscriptions_view')->name('subscriptions.view');

        Route::get('subscriptions/delete', 'Admin\SubscriptionController@subscriptions_delete')->name('subscriptions.delete');

        Route::get('subscriptions/status', 'Admin\SubscriptionController@subscriptions_status')->name('subscriptions.status');

        // Subscription Payments

        Route::get('subscription_payments/index','Admin\SubscriptionController@subscription_payments_index')->name('subscription_payments.index');

        Route::get('subscription_payments/view','Admin\SubscriptionController@subscription_payments_view')->name('subscription_payments.view');

        Route::get('revenues/dashboard','Admin\AdminRevenueController@revenues_dashboard')->name('revenues.dashboard');

        // Project Payments

        Route::get('project_payments/index','Admin\AdminProjectController@project_payments_index')->name('project_payments.index');

        Route::get('project_payments/view','Admin\AdminProjectController@project_payments_view')->name('project_payments.view');


        Route::get('token_payments/index','Admin\AdminRevenueController@token_payments_index')->name('token_payments.index');

        Route::get('token_payments/view','Admin\AdminRevenueController@token_payments_view')->name('token_payments.view');


        Route::get('project-view','Admin\AdminProjectController@projects_view_for_web')->name('projects_view_for_web');

        // Ajax Functions


        Route::post('projects/pool_contract_save','Admin\AdminProjectController@projects_pool_contract_save')->name('projects_pool_contract_save');

        Route::post('projects_burn_access_update','Admin\AdminProjectController@projects_burn_access_update')->name('projects_burn_access_update');

routes/web.php
<?php

use  App\Http\Controllers\UserAuthController;

use  App\Http\Controllers\AdminAuthController;

use  App\Http\Controllers\ReactController;

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::view('/{path?}', 'app');

// Route::get('/{path?}', [
//     'uses' => 'ReactController@show',
//     'as' => 'react',
//     'where' => ['path' => 'burn|mint|new']
// ]);

// Route::get('/project/{path?}', function () {
//     return view('app');
// })->where('path', '.*');

// 
// // Route::get('/{url?}', function () {
//     return view('app');
// })->where('', 'list');

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/test', function(){
    return view('test');
});

// User

Route::get('/', [UserAuthController::class, 'index'])->name('user.home') ->middleware('auth:web');

Route::get('/login', [UserAuthController::class, 'login'])->name('user.login');

Route::post('/login', [UserAuthController::class, 'handleLogin'])->name('user.handleLogin');

Route::get('/logout', [UserAuthController::class, 'index'])->name('user.logout');

Route::get('email', 'SampleController@email_check');

resources/views/admin/dashboard.blade.php
@extends('layouts.admin')

@section('content-header', tr('dashboard'))

@section('breadcrumb')

<li class="breadcrumb-item active">{{tr('dashboard')}}</li>

@endsection

@section('styles')

@endsection


@section('content')

	<div class="row">
		<div class="col-xl-3 col-md-6 col">
			<a href="{{route('admin.users.index')}}">
			    <div class="info-box info-box-css bg-dark">
			        <span class="info-box-icon"><i class="glyphicon glyphicon-user"></i></span>
			        <div class="info-box-content">
			            <span class="info-box-number">{{$data->total_users}}</span>
			            <span class="info-box-text">{{tr('total_users')}}</span>
			        </div>
			        <!-- /.info-box-content -->
			    </div>
			    <!-- /.info-box -->
			</a>
		
		</div>

		<div class="col-xl-3 col-md-6 col">
			<a href="{{route('admin.projects.index')}}">

			    <div class="info-box info-box-css bg-success">
			        <span class="info-box-icon"><i class="glyphicon glyphicon-book"></i></span>
			        <div class="info-box-content">
			            <span class="info-box-number">{{$data->total_projects}}</span>
			            <span class="info-box-text">{{tr('total_projects')}}</span>
			        </div>
			        <!-- /.info-box-content -->
			    </div>
			    <!-- /.info-box -->
			</a>
		
		</div>

	
        
    </div>

    <div class="row">
    	<div class="col-12 col-lg-12">
			<div class="box">
				<div class="box-header with-border">
				  	<h3 class="box-title">{{tr('last_6_months_projects')}}</h3>
				</div>
				<div class="box-body">
				  	<!-- <p class="text-muted"><i>{{tr('last_6_months_revenue_notes')}}</i></p> -->

				 	<div class="chart">
						<div id="e_chart_2" class="" style="height:400px;"></div>	
				  	</div>
				</div>
			</div>

	    </div>
	</div>

    <div class="row">

    	@if($data->recent_projects->count() > 0)

	    	<div class="col-md-6 col-lg-6">
	            <div class="box">
					<div class="box-header with-border">
	              		<h5 class="box-title">{{tr('recent_projects')}}</h5>
					</div>
					<div class="box-body p-0">
					  	
					  	<div class="media-list media-list-hover media-list-divided">

					  		@foreach($data->recent_projects as $v => $project)
								<a class="media media-single" href="{{route('admin.projects.view',['project_id' => $project->id])}}">
								  	<img class="avatar" src="{{$project->picture}}" alt="{{$project->name}}">
								  	<div class="media-body">
										<h6>{{$project->name ?? tr('not_available')}}</h6>
										<small class="text-fader">By {{$project->user->name ?? tr('not_available')}}</small>
								  	</div>
								  	<p style="float: right;">{{common_date($project->created_at , Auth::guard('admin')->user()->timezone)}}</p>
								</a>
							@endforeach
					  </div>
					</div>
	              <div class="text-center bt-1 border-light p-2">
	                <a class="text-uppercase d-block font-size-12" href="{{route('admin.projects.index')}}">See all</a>
	              </div>
	            </div>
	        </div>

        @endif

        @if($data->recent_users->count() > 0)
        <div class="col-md-6 col-lg-6">
            <div class="box">
				<div class="box-header with-border">
              		<h5 class="box-title">{{tr('recent_users')}}</h5>
				</div>
				<div class="box-body p-0">
				  	<div class="media-list media-list-hover media-list-divided">

				  		@foreach($data->recent_users as $v => $users)

							<div class="media media-single">
								
								<a href="{{route('admin.users.view',['user_id' => $users->id])}}">
									<img class="avatar" src="{{$users->picture}}" alt="{{$users->name}}">
								</a>

							  	<div class="media-body">
									<h6><a href="{{route('admin.users.view',['user_id' => $users->id])}}">{{$users->name ?? tr('not_available')}}</a></h6>
									<small class="text-fader">{{$users->email}}</small>
							  	</div>

							  	<p style="float: right;">{{common_date($users->created_at , Auth::guard('admin')->user()->timezone)}}</p>
							</div>

						@endforeach
				  	</div>
				</div>
            <div class="text-center bt-1 border-light p-2">
                <a class="text-uppercase d-block font-size-12" href="{{route('admin.users.index')}}">See All</a>
            </div>
        </div>
        @endif
    </div>


@endsection

@section('scripts')
	
	<script src="../assets/vendor_components/echarts-master/dist/echarts-en.min.js"></script>
	<script src="../assets/vendor_components/echarts-liquidfill-master/dist/echarts-liquidfill.min.js"></script>

    <script type="text/javascript">

    	$(window).on("load", function() {

    		var dom = document.getElementById("e_chart_2");
			var myChart = echarts.init(dom);
			var app = {};
			option = null;
			option = {
				color: ['#00c292'],
				textStyle: {
					color: '#666666'
				},
			    tooltip: {
			        trigger: 'axis'
			    },
			    legend: {
			        data:['the highest temperature','the lowest temperature']
			    },
				
			    xAxis:  {
			        type: 'category',
			        boundaryGap: false,
			        data: [<?php foreach ($data->analytics->last_x_days_projects as $key => $value) {
                        echo '"' . $value->formatted_month . '"' . ',';
                    }
                    ?>]
			    },
			    yAxis: {
			        type: 'value',
			        axisLabel: {
			            formatter: '{value}'
			        }
			    },
			    series: [
			        {
			            name:'Projects',
			            type:'line',
			            data:[<?php foreach ($data->analytics->last_x_days_projects as $key => $value) {
                        echo '"' . $value->total_projects . '"' . ',';
                    }
                    ?>],
			            markPoint: {
			                data: [
			                    {type: 'max', name: 'Maximum'},
			                    {type: 'min', name: 'Minimum'}
			                ]
			            },
			            markLine: {
			                data: [
			                    {type: 'average', name: 'Average'}
			                ]
			            }
			        }
			    ]
			};
			if (option && typeof option === "object") {
			    myChart.setOption(option, true);
			}

		});

    </script>
@endsection

resources/views/admin/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in as Admin!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/login.blade.php
@extends('layouts.appadmin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Admin Login') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('admin.handleLogin') }}">
                        @csrf

                        <input type="hidden" name="timezone" value="" id="userTimezone">

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') ?? Setting::get('demo_admin_email') }}" required autocomplete="email" autofocus>

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="current-password" value="{{ Setting::get('demo_admin_email') }}">

                                @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-6 offset-md-4">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="remember" id="remember" {{ old('remember') ? 'checked' : '' }}>

                                    <label class="form-check-label" for="remember">
                                        {{ __('Remember Me') }}
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Login') }}
                                </button>

                                @if (Route::has('password.request'))
                                    <a class="btn btn-link" href="{{ route('password.request') }}">
                                        {{ __('Forgot Your Password?') }}
                                    </a>
                                @endif
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')

<script src="{{asset('assets/js/jstz.min.js')}}"></script>
<script>
    $(document).ready(function() {

        var dMin = new Date().getTimezoneOffset();
        var dtz = -(dMin/60);
        // alert(dtz);
        $("#userTimezone").val(jstz.determine().name());
    });

</script>

@endsection