routes/admin.php
<?php

Route::group(['middleware' => 'web'], function() {

    Route::group(['as' => 'admin.'], function() {

        Route::get('/clear-cache', function() {

            $exitCode = Artisan::call('config:cache');

            return back();

        })->name('clear-cache');


        Route::get('login', 'Auth\AdminLoginController@showLoginForm')->name('login');

        Route::post('login', 'Auth\AdminLoginController@login')->name('login.post');

        Route::get('logout', 'Auth\AdminLoginController@logout')->name('logout');

        Route::get('/', 'Admin\AdminController@dashboard')->name('dashboard');

        Route::get('forgot_password','Auth\AdminLoginController@showLinkRequestForm')->name('forgot_password.request');

        Route::post('forgot_password_update', 'Auth\AdminLoginController@forgot_password_update')->name('forgot_password.update');

        // Users CRUD Operations

        Route::get('users', 'Admin\AdminUserController@users_index')->name('users.index');

        Route::get('users/create', 'Admin\AdminUserController@users_create')->name('users.create');

        Route::get('users/edit', 'Admin\AdminUserController@users_edit')->name('users.edit');

        Route::post('users/save', 'Admin\AdminUserController@users_save')->name('users.save');

        Route::get('users/view', 'Admin\AdminUserController@users_view')->name('users.view');

        Route::get('users/delete', 'Admin\AdminUserController@users_delete')->name('users.delete');

        Route::get('users/status', 'Admin\AdminUserController@users_status')->name('users.status');

        Route::get('users/excel','Admin\AdminUserController@users_excel')->name('users.excel');

        Route::get('users/verify', 'Admin\AdminUserController@users_verify_status')->name('users.verify');

        Route::get('users/export/','Admin\AdminUserController@users_export')->name('users.export');

        Route::get('invested_projects', 'Admin\AdminUserController@invested_projects')->name('invested_projects');

        Route::get('invested_projects/view', 'Admin\AdminUserController@invested_projects_view')->name('invested_projects.view');

        Route::get('invested_projects/claim', 'Admin\AdminUserController@invested_projects_claim')->name('invested_projects.claim');
        
        Route::post('/users/bulk_action', 'Admin\AdminUserController@users_bulk_action')->name('users.bulk_action');

        Route::get('/users/staked_amount', 'Admin\AdminUserController@users_staked_amount')->name('users.staked_amount');

        
        Route::post('subscriptions/bulk_action', 'Admin\SubscriptionController@subscriptions_bulk_action')->name('subscriptions.bulk_action');


        Route::get('profile', 'Admin\AdminAccountController@profile')->name('profile');

        Route::post('profile/save', 'Admin\AdminAccountController@profile_save')->name('profile.save');

        Route::post('change/password', 'Admin\AdminAccountController@change_password')->name('change.password');
        
        Route::get('transactions/getaccount', 'Admin\BlockOperationController@transactions_getaccount')->name('transactions.getaccount');

        Route::post('transactions/history', 'Admin\BlockOperationController@transactions_index')->name('transactions.index');

        Route::get('wallets/view', 'Admin\BlockOperationController@transactions_getaccount')->name('wallets.view');

        // settings

        Route::get('control', 'Admin\AdminSettingController@settings_control')->name('settings-control'); 

        Route::get('settings', 'Admin\AdminSettingController@settings')->name('settings'); 

        Route::post('settings/save', 'Admin\AdminSettingController@settings_save')->name('settings.save'); 

        Route::post('env_settings','Admin\AdminSettingController@env_settings_save')->name('env-settings.save');

        // Documents CRUD operations

        Route::get('documents/index', 'Admin\AdminLookupController@documents_index')->name('documents.index');

        Route::get('documents/create', 'Admin\AdminLookupController@documents_create')->name('documents.create');
 
        Route::get('documents/edit', 'Admin\AdminLookupController@documents_edit')->name('documents.edit');
 
        Route::post('documents/save', 'Admin\AdminLookupController@documents_save')->name('documents.save');
 
        Route::get('documents/view', 'Admin\AdminLookupController@documents_view')->name('documents.view');
 
        Route::get('documents/delete', 'Admin\AdminLookupController@documents_delete')->name('documents.delete');
 
        Route::get('documents/status', 'Admin\AdminLookupController@documents_status')->name('documents.status');
 
        //user documents 

        Route::get('user-documents', 'Admin\AdminUserController@user_documents_index')->name('user_documents.index');

        Route::get('user-document', 'Admin\AdminUserController@user_documents_view')->name('user_documents.view');

        Route::get('user-documents/verify', 'Admin\AdminUserController@user_documents_verify')->name('user_documents.verify');

        // STATIC PAGES

        Route::get('static_pages' , 'Admin\AdminLookupController@static_pages_index')->name('static_pages.index');

        Route::get('static_pages/create', 'Admin\AdminLookupController@static_pages_create')->name('static_pages.create');

        Route::get('static_pages/edit', 'Admin\AdminLookupController@static_pages_edit')->name('static_pages.edit');

        Route::post('static_pages/save', 'Admin\AdminLookupController@static_pages_save')->name('static_pages.save');

        Route::get('static_pages/delete', 'Admin\AdminLookupController@static_pages_delete')->name('static_pages.delete');

        Route::get('static_pages/view', 'Admin\AdminLookupController@static_pages_view')->name('static_pages.view');

        Route::get('static_pages/status', 'Admin\AdminLookupController@static_pages_status_change')->name('static_pages.status');

        //faq CRUD
        Route::get('faqs', 'Admin\AdminLookupController@faqs_index')->name('faqs.index');

        Route::get('faqs/create', 'Admin\AdminLookupController@faqs_create')->name('faqs.create');

        Route::get('faqs/edit', 'Admin\AdminLookupController@faqs_edit')->name('faqs.edit');

        Route::post('faqs/save', 'Admin\AdminLookupController@faqs_save')->name('faqs.save');

        Route::get('faqs/view', 'Admin\AdminLookupController@faqs_view')->name('faqs.view');

        Route::get('faqs/delete', 'Admin\AdminLookupController@faqs_delete')->name('faqs.delete');

        Route::get('faqs/status', 'Admin\AdminLookupController@faqs_status')->name('faqs.status');
        //faq end

        Route::get('projects', 'Admin\AdminProjectController@projects_index')->name('projects.index');

        Route::get('projects/create', 'Admin\AdminProjectController@projects_create')->name('projects.create');

        Route::get('projects/edit', 'Admin\AdminProjectController@projects_edit')->name('projects.edit');

        Route::post('projects/save', 'Admin\AdminProjectController@projects_save')->name('projects.save');

        Route::get('projects/view', 'Admin\AdminProjectController@projects_view')->name('projects.view');

        Route::get('projects/delete', 'Admin\AdminProjectController@projects_delete')->name('projects.delete');

        Route::get('projects/status', 'Admin\AdminProjectController@projects_status')->name('projects.status');

        Route::get('projects/publish_status', 'Admin\AdminProjectController@projects_publish_status')->name('projects.publish_status');

        // Subscriptions
        
        Route::get('subscriptions', 'Admin\SubscriptionController@subscriptions_index')->name('subscriptions.index');

        Route::get('subscriptions/create', 'Admin\SubscriptionController@subscriptions_create')->name('subscriptions.create');

        Route::get('subscriptions/edit', 'Admin\SubscriptionController@subscriptions_edit')->name('subscriptions.edit');

        Route::post('subscriptions/save', 'Admin\SubscriptionController@subscriptions_save')->name('subscriptions.save');

        Route::get('subscriptions/view', 'Admin\SubscriptionController@subscriptions_view')->name('subscriptions.view');

        Route::get('subscriptions/delete', 'Admin\SubscriptionController@subscriptions_delete')->name('subscriptions.delete');

        Route::get('subscriptions/status', 'Admin\SubscriptionController@subscriptions_status')->name('subscriptions.status');

        // Subscription Payments

        Route::get('subscription_payments/index','Admin\SubscriptionController@subscription_payments_index')->name('subscription_payments.index');

        Route::get('subscription_payments/view','Admin\SubscriptionController@subscription_payments_view')->name('subscription_payments.view');

        Route::get('revenues/dashboard','Admin\AdminRevenueController@revenues_dashboard')->name('revenues.dashboard');

        // Project Payments

        Route::get('project_payments/index','Admin\AdminProjectController@project_payments_index')->name('project_payments.index');

        Route::get('project_payments/view','Admin\AdminProjectController@project_payments_view')->name('project_payments.view');


        Route::get('token_payments/index','Admin\AdminRevenueController@token_payments_index')->name('token_payments.index');

        Route::get('token_payments/view','Admin\AdminRevenueController@token_payments_view')->name('token_payments.view');


        Route::get('project-view','Admin\AdminProjectController@projects_view_for_web')->name('projects_view_for_web');

        // Ajax Functions


        Route::post('projects/pool_contract_save','Admin\AdminProjectController@projects_pool_contract_save')->name('projects_pool_contract_save');

        Route::post('projects_burn_access_update','Admin\AdminProjectController@projects_burn_access_update')->name('projects_burn_access_update');

routes/web.php
<?php

use  App\Http\Controllers\UserAuthController;

use  App\Http\Controllers\AdminAuthController;

use  App\Http\Controllers\ReactController;

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::view('/{path?}', 'app');

// Route::get('/{path?}', [
//     'uses' => 'ReactController@show',
//     'as' => 'react',
//     'where' => ['path' => 'burn|mint|new']
// ]);

// Route::get('/project/{path?}', function () {
//     return view('app');
// })->where('path', '.*');

// 
// // Route::get('/{url?}', function () {
//     return view('app');
// })->where('', 'list');

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/test', function(){
    return view('test');
});

// User

Route::get('/', [UserAuthController::class, 'index'])->name('user.home') ->middleware('auth:web');

Route::get('/login', [UserAuthController::class, 'login'])->name('user.login');

Route::post('/login', [UserAuthController::class, 'handleLogin'])->name('user.handleLogin');

Route::get('/logout', [UserAuthController::class, 'index'])->name('user.logout');

Route::get('email', 'SampleController@email_check');

app/Models/StaticPage.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;

use Illuminate\Database\Eloquent\Model;

class StaticPage extends Model
{
    use HasFactory;

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = ['id', 'unique_id'];

    protected $appends = ['static_page_id', 'static_page_unique_id'];

    public function getStaticPageIdAttribute() {

        return $this->id;
    }

    public function getStaticPageUniqueIdAttribute() {

        return $this->unique_id;
    }
}

resources/views/admin/static_pages/_form.blade.php
<div class="row">

    <div class="col-lg-12 col-12">

        <div class="box">

            <div class="box-header with-border">

                <h3 class="box-title">{{ $static_page->id ? tr('edit_static_page') : tr('add_static_page') }}</h3>

            </div>

            <form class="form-horizontal" action="{{(Setting::get('is_demo_control_enabled') == YES) ? '#' : route('admin.static_pages.save') }}" method="POST" enctype="multipart/form-data" role="form">
               
                @csrf


                @if($static_page->id)

                    <input type="hidden" name="static_page_id" value="{{$static_page->id}}">

                @endif

                <div class="box-body">

                    <div class="row">

                        <div class="form-group col-md-6">
                            <div class="form-group-1">
                                <label for="title">{{tr('title')}}<span class="admin-required">*</span> </label>
                                <input type="text" id="title" name="title" class="form-control" placeholder="Enter {{tr('title')}}" required  value="{{old('title')?: $static_page->title}}" onkeydown="return alphaOnly(event);">
                            </div>
                        </div>

                        <div class="form-group col-md-6">

                            <label for="page">
                                {{tr('select_static_page_type')}}
                                <span class="required" aria-required="true"> <span class="admin-required">*</span> </span>
                            </label>
                            
                            <select class="form-control select2" name="type" required>
                                <option value="">{{tr('select_static_page_type')}}</option>

                                @foreach($static_keys as $value)

                                    <option value="{{$value}}" @if($value == $static_page->type) selected="true" @endif>{{ ucfirst($value) }}</option>

                                @endforeach 
                            </select>
                            
                        </div>
                    </div>
                    
                    <div class="row">

                        <div class="col-md-12"> 

                            <div class="form-group">

                                <label for="description">{{tr('description')}}<span class="admin-required">*</span></label>

                                <textarea id="summernote" rows="5" class="form-control" required name="description" placeholder="{{ tr('description') }}">{{old('description') ?: $static_page->description}}</textarea>

                            </div>

                        </div>

                    </div>

                </div>

                <div class="box-footer">
                    
                    <button type="reset" class="btn btn-warning btn-default btn-squared px-30">Reset</button>

                    <button type="submit" class="btn btn-info pull-right">Submit</button>

                </div>

            </form>
        
        </div>
    
    </div>

</section>

resources/views/admin/static_pages/create.blade.php
@extends('layouts.admin')

@section('title', tr('add_static_page'))

@section('content-header',tr('static_pages'))

@section('styles')

<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">

@endsection

@section('breadcrumb')

    <li class="breadcrumb-item">
    	<a href="{{ route('admin.static_pages.index') }}">{{tr('static_pages')}}</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
    	<span>{{tr('add_static_page')}}</span>
    </li>
           
@endsection 

@section('content')
    
    @include('admin.static_pages._form')

@endsection

@section('scripts')

<script src="{{asset('js/summernote.min.js')}}"></script>

<script>
    $(document).ready(function() {
        $('#summernote').summernote();
    });
  </script>

@endsection

resources/views/admin/static_pages/edit.blade.php
@extends('layouts.admin')

@section('title', tr('edit_static_page'))

@section('content-header',tr('static_pages'))

@section('styles')

<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">

@endsection

@section('breadcrumb')

    
    <li class="breadcrumb-item">
    	<a href="{{ route('admin.static_pages.index') }}">{{tr('static_pages')}}</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
    	<span>{{tr('edit_static_page')}}</span>
    </li>
           
@endsection 

@section('content')
    
    @include('admin.static_pages._form')

@endsection

@section('scripts')

<script src="{{asset('js/summernote.min.js')}}"></script>

<script>
    $(document).ready(function() {
        $('#summernote').summernote();
    });
  </script>

@endsection

resources/views/admin/static_pages/index.blade.php
@extends('layouts.admin') 

@section('content-header', tr('static_pages'))

@section('breadcrumb')

    <li class="breadcrumb-item"><a href="{{ route('admin.static_pages.index' )}}">{{tr('static_pages')}}</a></li>

    <li class="breadcrumb-item active" aria-current="page">
        <span>{{ tr('view_static_pages') }}</span>
    </li>
           
@endsection 

@section('content')

<div class="row">
    
    <div class="col-md-12">

        <div class="box">

            <div class="box-header with-border">

                <h3 class="box-title">{{ tr('view_static_pages') }}</h3>

                <div class="heading-elements pull-right">
                    <a href="{{ route('admin.static_pages.create') }}" class="btn btn-primary"><i class="ft-plus icon-left"></i>{{ tr('add_static_page') }}</a>
                </div>
                    
            </div>

            <div class="box-body">

                <div class="callout bg-pale-secondary">
                    <h4>Notes:</h4>
                    <p>
                        <ul>
                            <li>You can add content to your pages like terms and conditions, Privacy policy, etc,.</li>
                        </ul>
                    </p>
                </div>

                <div class="table-responsive">
                    
                    <table id="example2" class="table table-bordered table-hover display nowrap margin-top-10 w-p100">
                        <thead>
                            <tr>
                                <th>{{tr('s_no')}}</th>
                                <th>{{tr('page_title')}}</th>
                                <th>{{tr('static_page_type')}}</th>
                                <th>{{tr('status')}}</th>
                                <th>{{tr('action')}}</th>
                            </tr>
                        </thead>

                        <tbody>


                            @foreach($static_pages as $i => $static_page)

                                <tr>
                                    <td>{{$i+$static_pages->firstItem()}}</td>

                                    <td>
                                        <a href="{{route('admin.static_pages.view' , ['static_page_id'=> $static_page->id] )}}"> {{$static_page->title}}</a>
                                    </td>

                                    <td class="text-capitalize">{{$static_page->type}}</td>

                                    <td>
                                        @if($static_page->status == APPROVED)

                                          <span class="label label-success">{{tr('approved')}}</span> 

                                        @else

                                          <span class="label label-warning">{{tr('pending')}}</span> 
                                        @endif
                                    </td>

                                    <td>  

                                        <div class="btn-group" role="group">

                                            <button class="btn btn-primary dropdown-toggle dropdown-menu-right" id="btnGroupDrop1" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="ft-settings icon-left"></i> {{ tr('action') }}</button>

                                            <div class="dropdown-menu" aria-labelledby="dropdownMenuOutlineButton1">

                                                <a class="dropdown-item" href="{{ route('admin.static_pages.view', ['static_page_id' => $static_page->id] ) }}">
                                                    {{tr('view')}}
                                                </a>

                                                @if(Setting::get('is_demo_control_enabled') == NO)
                                                
                                                    <a class="dropdown-item" href="{{ route('admin.static_pages.edit', ['static_page_id' => $static_page->id] ) }}">
                                                        {{tr('edit')}}
                                                    </a>

                                                    <a class="dropdown-item" 
                                                    onclick="return confirm(&quot;{{tr('static_page_delete_confirmation' , $static_page->title)}}&quot;);" href="{{ route('admin.static_pages.delete', ['static_page_id' => $static_page->id,'page'=>request()->input('page')] ) }}" >
                                                        {{ tr('delete') }}
                                                    </a>

                                                @else

                                                    <a class="dropdown-item text-muted" href="javascript:;">{{tr('edit')}}</a>

                                                    <a class="dropdown-item text-muted" href="javascript:;">{{ tr('delete') }}</a>

                                                @endif                  

                                                <div class="dropdown-divider"></div>

                                                @if($static_page->status == APPROVED)

                                                    <a class="dropdown-item" href="{{ route('admin.static_pages.status', ['static_page_id' =>  $static_page->id] ) }}" 
                                                    onclick="return confirm(&quot;{{$static_page->title}} - {{tr('static_page_decline_confirmation')}}&quot;);"> 
                                                        {{tr('decline')}}
                                                    </a>

                                                @else

                                                    <a class="dropdown-item" href="{{ route('admin.static_pages.status', ['static_page_id' =>  $static_page->id] ) }}">
                                                        {{tr('approve')}}
                                                    </a>
                                                       
                                                @endif

                                            </div>
                                             
                                        </div>
                                    

                                    </td>
                                
                                </tr>

                            @endforeach

                        </tbody>
                        
                    </table>

                </div>

            </div>

            <div class="box-footer clearfix">
                    
                <div class="pull-right rd-flex">{{ $static_pages->appends(request()->input())->links('pagination::bootstrap-4') }}</div>
            </div>

        </div>

    </div>

</section>

@endsection

resources/views/admin/static_pages/view.blade.php
@extends('layouts.admin') 

@section('title', tr('view_static_page'))

@section('content-header',tr('static_pages'))

@section('breadcrumb')

    <li class="breadcrumb-item"><a href="{{route('admin.static_pages.index')}}">{{tr('static_pages')}}</a></li>

    <li class="breadcrumb-item active" aria-current="page">
        <span>{{tr('view_static_page')}}</span>
    </li>
           
@endsection  

@section('content')

    
<div class="row match-height">

    <div class="col-lg-6 col-12">
        
        <div class="box">
            
            <div class="box-body">
                <div class="table-responsive">
                    <table class="table table-striped table-hover no-margin">
                        <tbody>
                            <tr>
                                <th>{{tr('page_title')}}</th>
                                <td>{{$static_page->title}}</td>
                            </tr>
                            <tr>
                                <th>{{tr('static_page_type')}}</th>
                                <td>{{$static_page->type}}</td>
                            </tr>
                            
                            <tr>
                                <th>{{tr('status')}}</th>
                                <td class="text-capitalize">
                                    @if($static_page->status == APPROVED)

                                        <span class="badge badge-success badge-md text-uppercase">{{tr('approved')}}</span>

                                    @else 

                                        <span class="badge badge-danger badge-md text-uppercase">{{tr('pending')}}</span>

                                    @endif

                                </td>
                            </tr>

                            <tr>
                                <th>{{tr('created_at')}}</th>
                                <td>{{ common_date($static_page->created_at,Auth::guard('admin')->user()->timezone) }}</td>
                            </tr>

                            <tr>
                                <th>{{tr('updated_at')}}</th>
                                <td>{{ common_date($static_page->updated_at,Auth::guard('admin')->user()->timezone) }}</td>
                            </tr>


                        </tbody>
                    </table>
                </div>
            </div>
            <!-- /.box-body -->
         </div>
    </div>

    <div class="col-lg-6 col-12">

        <div class="box">
            
            <div class="box-body">

                <div class="media-list media-list-divided">

                    <div class="media media-single">

                        @if($static_page->status == APPROVED)

                            <div class="media-right">

                                <a class="btn bg-navy margin" href="{{  route('admin.static_pages.status' , ['static_page_id' => $static_page->id] )  }}" onclick="return confirm(&quot;{{ $static_page->title }} - {{ tr('static_page_decline_confirmation') }}&quot;);"> <i class="fa fa-check"></i>  {{ tr('decline') }}
                                                </a>
                            </div>

                        @else

                            <div class="media-right">

                                <a class="btn bg-navy margin" href="{{ route('admin.static_pages.status' , ['static_page_id' => $static_page->id] ) }}"> <i class="fa fa-check"></i>  {{ tr('approve') }}</a>
                            </div>

                        @endif

                        @if(Setting::get('is_demo_control_enabled') == YES)

                            <div class="media-right">
                                <button class="btn bg-purple margin"><i class="fa fa-edit"></i> {{tr('edit')}}</button>
                            </div>

                            <div class="media-right">
                                <button class="btn bg-olive margin"><i class="fa fa-trash"></i> {{tr('delete')}}</button>
                            </div>

                        @else

                            <div class="media-right">

                                <a class="btn bg-purple margin" href="{{ route('admin.static_pages.edit', ['static_page_id' => $static_page->id] ) }}"><i class="fa fa-edit"></i> {{tr('edit')}}</a>
                            </div>  

                            <div class="media-right">

                                <a class="btn bg-olive margin" onclick="return confirm(&quot;{{ tr('static_page_delete_confirmation' , $static_page->title) }}&quot;);" href="{{ route('admin.static_pages.delete', ['static_page_id' => $static_page->id] ) }}"><i class="fa fa-trash"></i> {{tr('delete')}}</a>
                            </div>

                           

                        @endif

                    </div>
                </div>
            </div>

            <div class="box-body">

                <h4 class="box-title">{{ tr('description') }}</h4>
        
                <p class="card-text"><?= $static_page->description ?></p>
                
            </div>

        </div>
    </div>

</div>


@endsection